CREATE DATABASE shard0
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
;

USE shard0;

CREATE TABLE `test_0` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `test_1` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `test_2` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `test_3` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;


CREATE DATABASE shard1
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
;

USE shard1;

CREATE TABLE `test_0` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `test_1` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `test_2` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `test_3` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a`  INT(11) DEFAULT NULL,
  `b`  INT(11) DEFAULT NULL,
  `c`  INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;